### ISSUE TITLE
Any source code?

### ISSUE THREAD

**Issue by NightYoshi370** [BlackB1RD-Development/blackb1rd-bot#1]
I mean, github is a service where people can upload source code. What's the point of having a repository if you aren't going to put the source code?

**Comment by JamesParkDev** [comment]
This repository is for locals but, for source code of the bot I'm pretty sure it's closed you need to wait for the owner.

**Comment by RealBlackB1RD** [comment]
As you said, GitHub is a service where people can upload source code but, this repository isn't storing any source code.
The point of having a repository if there's no source code is for translation purpose, as I did here. I can just redirect people to this repository if they want to help with the bot translation.
They just fork the repository, edit their language file, making a pull request, we're checking it, accepting it if it's meet our requirements and then migrating it into the bot, so it's that easy for us, and for the community.

If you have any further question, feel free to ask.
